pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':unityLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
        // Azure Spatial Anchors 2.x Android NDK artifacts are not available
        // from Maven Central, but this project still depends on them.
        maven {
            url 'https://artifactory.appodeal.com/appodeal-public/'
        }
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}
